import pandas as pd
from data_processing.Input_Data import load_file_as_dataframe
from data_processing.Data_Aggregate import aggregate_store_monthly, aggregate_warehouse_monthly, aggregate_dc_monthly
from echelon_aggregation.Store import store_data
from echelon_aggregation.Warehouse import warehouse_data
from echelon_aggregation.DC import dc_data
from distribution.dc_distribution import dc_distribution
from distribution.warehouse_distribution import warehouse_distribution
from schedules import store_schedule
from schedules import warehouse_schedule
from Preassumptions import STORE_SCHEDULE,WAREHOUSE_SCHEDULE
from config import input_path,monthly_demand_path,calculated_metrics_path,distribution_path,schedule_path
from app_function_call import aggregate,calculate_metrics,distribute,schedule,download



df = load_file_as_dataframe(input_path, date_col="Time.[Week]")

store_df,warehouse_df,dc_df=aggregate(df)

store_demand_df,warehouse_demand_df,dc_demand_df=calculate_metrics(store_df,warehouse_df,dc_df)

warehouse_store_distribution,dc_warehouse_distribution=distribute(dc_demand_df,warehouse_demand_df,store_demand_df)

store_schedule_df,warehouse_schedule_df=schedule(store_demand_df,warehouse_demand_df)

download(store_df,warehouse_df,dc_df,store_demand_df,warehouse_demand_df,dc_demand_df,warehouse_store_distribution,dc_warehouse_distribution,store_schedule_df,warehouse_schedule_df)
